version: '3.7'

services:
    dev:
        image: gxxtech/api-foodzup:0.3
        command: npm run start:dev
        restart: always
        ports:
            - 8000:8000
        networks:
            - nesjs-network
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules

networks:
    nesjs-network: