apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f stack.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "3366"
      port: 3366
      targetPort: 3306
  selector:
    io.kompose.service: db
  type: LoadBalancer
status:
  loadBalancer:
